AWSTemplateFormatVersion: 2010-09-09
Parameters:
  CodeBuildProjectName:
    Description: Name of CodeBuild project to run
    Type: String

Resources:  
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - 
            Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service:
                - lambda.amazonaws.com
      Path: "/"
      Policies:
        - 
          PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: Allow
                Resource: arn:aws:logs:*:*:*
                Action: 
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
              - Effect: Allow
                Resource: arn:aws:codebuild:*:*:*
                Action:
                  - codebuild:StartBuild
                  - codebuild:GetBatch*

  CustomResourceLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: oramco-cfn
        S3Key: oramco/cfn-codebuild-trigger-and-wait/src.zip
      Handler: CustomResource.CodeBuild::OramCo.CloudFormation.CustomResource.CodeBuild.BuildAndWait::Execute
      Runtime: dotnetcore2.1
      Timeout: 600
      Role: !GetAtt LambdaExecutionRole.Arn

  CustomResource:
    Type: "Custom::MyCustomResource"
    Properties:
      ServiceToken: !GetAtt CustomResourceLambdaFunction.Arn
      CodeBuildProjectName: !Ref CodeBuildProjectName      